# Generated by Django 5.0.2 on 2026-01-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='district',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='problem_summary',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='animal_type',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='call_sid',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='source',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='state',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='urgency',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='village',
        ),
        migrations.AddField(
            model_name='complaint',
            name='caller_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='REGISTERED', max_length=20),
        ),
    ]
