# Generated by Django 5.0.2 on 2026-01-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_district_complaint_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='call_sid',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='language',
            field=models.CharField(default='hi-IN', max_length=10),
        ),
    ]
