# Generated by Django 5.0.2 on 2026-02-05 10:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_complaint_call_sid_complaint_complaint_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('call_type', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], db_index=True, max_length=10)),
                ('duration', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('busy', 'Busy'), ('failed', 'Failed'), ('no-answer', 'No Answer'), ('cancelled', 'Cancelled'), ('in-progress', 'In Progress')], db_index=True, default='in-progress', max_length=20)),
                ('recording_url', models.URLField(blank=True, max_length=500, null=True)),
                ('from_number', models.CharField(blank=True, max_length=20)),
                ('to_number', models.CharField(blank=True, max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='complaint',
            name='area_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='area_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='consumer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='meter_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['meter_no', 'area_code'], name='home_compla_meter_n_8c91dc_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['verified', 'status'], name='home_compla_verifie_bec51a_idx'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='home.complaint'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['call_type', 'status'], name='home_calllo_call_ty_bf0602_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['phone_number', '-created_at'], name='home_calllo_phone_n_69c871_idx'),
        ),
    ]
