# Generated by Django 5.0.2 on 2026-01-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_complaint_call_sid_complaint_complaint_json_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='complaint',
            name='area_code',
            field=models.CharField(blank=True, db_index=True, help_text='Area code (e.g., MM001, GJ001)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='area_name',
            field=models.CharField(blank=True, help_text='Area name (e.g., Madan Mahal)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='consumer_name',
            field=models.CharField(blank=True, help_text='Verified consumer name from registry', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='meter_no',
            field=models.CharField(blank=True, db_index=True, help_text='Verified meter/consumer ID', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='verified',
            field=models.BooleanField(default=False, help_text='True if both meter and name were verified'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['meter_no', 'area_code'], name='home_compla_meter_n_8c91dc_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['verified', 'status'], name='home_compla_verifie_bec51a_idx'),
        ),
    ]
