# Generated by Django 5.0.2 on 2026-02-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_calllog_alter_complaint_options_complaint_area_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='transcript_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='recommended_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sentiment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='urgency',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['transcript_processed'], name='home_calllo_transcr_796b80_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['urgency', 'sentiment'], name='home_compla_urgency_cc33b8_idx'),
        ),
    ]
