# Generated by Django 5.0.2 on 2026-02-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_calllog_alter_complaint_options_complaint_area_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllog",
            name="recording_duration",
            field=models.IntegerField(
                default=0, help_text="Recording duration in seconds"
            ),
        ),
        migrations.AddField(
            model_name="calllog",
            name="recording_sid",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Twilio Recording SID",
                max_length=255,
                null=True,
            ),
        ),
    ]
