# Generated by Django 5.0.2 on 2026-02-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_calllog_transcript_calllog_transcript_processed_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calllog',
            name='home_calllo_transcr_796b80_idx',
        ),
        migrations.RemoveIndex(
            model_name='complaint',
            name='home_compla_urgency_cc33b8_idx',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='transcript',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='transcript_processed',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='ai_processed',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='ai_summary',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='recommended_action',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='transcript',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='urgency',
        ),
    ]
